services:
  app:
    image: registry.tako.co.id/tako-apps-dev/customer-ppjk:dev-latest
    container_name: laravel-app
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_SECOND_DATABASE}
      - DB_USERNAME=${DB_SECOND_USERNAME}
      - DB_PASSWORD=${DB_SECOND_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REVERB_HOST=reverb
      - APP_URL=${APP_URL}
      - FILESYSTEM_DISK=${FILESYSTEM_DISK:-public}
    volumes:
      - ./storage/app/public:/var/www/html/storage/app/public
      - /mnt/Ppjk:/mnt/Ppjk
      - /etc/hosts:/tmp/hosts_external:ro
    depends_on:
      - db
      - redis
    networks:
      - app-network

  reverb:
    image: registry.tako.co.id/tako-apps-dev/customer-ppjk:dev-latest
    container_name: laravel-reverb
    restart: always
    working_dir: /var/www/html
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - '8080:8080'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_SECOND_DATABASE}
      - DB_USERNAME=${DB_SECOND_USERNAME}
      - DB_PASSWORD=${DB_SECOND_PASSWORD}
    depends_on:
      - redis
    networks:
      - app-network

  queue:
    image: registry.tako.co.id/tako-apps-dev/customer-ppjk:dev-latest
    container_name: laravel-queue
    restart: always
    working_dir: /var/www/html
    command: php artisan queue:work --sleep=1 --tries=3
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REVERB_HOST=reverb
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_SECOND_DATABASE}
      - DB_USERNAME=${DB_SECOND_USERNAME}
      - DB_PASSWORD=${DB_SECOND_PASSWORD}
    depends_on:
      - redis
      - db
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis-cache
    restart: always
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_SECOND_DATABASE}
      POSTGRES_USER: ${DB_SECOND_USERNAME}
      POSTGRES_PASSWORD: ${DB_SECOND_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '${DB_SECOND_PORT:-5432}:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis-data:
